appId: 1234567890abcdefghijklmnopqrstuvwxyz

workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      groups:
        - firebase_secrets # Este grupo deve conter a variável FIREBASE_JSON_PATH
      # Adicione uma variável simples se a sintaxe 'secrets' falhar:
      vars:
        FIREBASE_JSON_FILENAME: google-services.json # Mapeia o nome do arquivo

    # REMOVA COMPLETAMENTE O BLOCO SECRETS AQUI!

    scripts:
      - name: Set up Flutter
        script: |
          flutter packages get

      - name: Setup Firebase Config (CRUCIAL)
        script: | 
          # Comando para copiar o arquivo secreto. 
          # Usamos o caminho da variável injetada, que aponta para o arquivo:
          cp "$FIREBASE_JSON_PATH" "$CM_BUILD_DIR/android/app/google-services.json"

      - name: Flutter build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk