
appId: 1234567890abcdefghijklmnopqrstuvwxyz # Mantenha esta linha como está

workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      groups:
        - firebase_secrets

    secrets:
      FIREBASE_JSON_PATH: google-services.json
    
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages get

      - name: Setup Firebase Config (CRUCIAL)
        script: | 
          cp "$FIREBASE_JSON_PATH" "$CM_BUILD_DIR/android/app/google-services.json"

      - name: Flutter build APK
        script: |
          # Comando para construir o arquivo APK final
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk