appId: 1234567890abcdefghijklmnopqrstuvwxyz

workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      groups:
        - firebase_secrets # O Codemagic injeta os segredos neste grupo,
                          # e a variável CM_SECRETS aponta para a pasta.
      # REMOÇÃO: Removido o bloco 'vars' para simplificar
      
    # REMOÇÃO: O bloco 'secrets' continua removido.

    scripts:
      - name: Set up Flutter
        script: |
          flutter packages get

      - name: Setup Firebase Config (CRUCIAL)
        script: | 
          # CORREÇÃO: Usamos a variável mágica CM_SECRETS mais o nome do arquivo.
          # Isso contorna o problema de a variável FIREBASE_JSON_PATH estar vazia.
          cp "$FIREBASE_JSON_PATH" "$CM_BUILD_DIR/android/app/google-services.json"

      - name: Flutter build APK
        script: |
          flutter build apk --release

    artifacts:

      - build/app/outputs/flutter-apk/app-release.apk
