appId: 1234567890abcdefghijklmnopqrstuvwxyz

workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      groups:
        - firebase_secrets 
      
    scripts:
      - name: Clean Packages and Get Dependencies
        script: |
          flutter packages get

      - name: Setup Firebase Config (CRUCIAL)
        script: | 
          cp "$CM_SECRETS/google-services.json" "$CM_BUILD_DIR/android/app/google-services.json" || true
          cp -f "$CM_BUILD_DIR/google-services.json" "$CM_BUILD_DIR/android/app/google-services.json" || true
          ls -la "$CM_BUILD_DIR/android/app/google-services.json"

      - name: Set Gradle Wrapper Permissions
        script: |
          chmod +x $CM_BUILD_DIR/android/gradlew

      - name: Build APK via Gradle Direto (ÚLTIMA TENTATIVA)
        script: |
          cd $CM_BUILD_DIR/android
          ./gradlew assembleRelease \
            --info \
            --stacktrace \
            -x lint \
            -Dorg.gradle.caching=false \
            -Dorg.gradle.jvmargs='-Xmx2048m'

          cd $CM_BUILD_DIR
          ls -R build/app/outputs/
          ls -R app/build/outputs/

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

