# Nome da sua Aplicação no Codemagic
appId: 1234567890abcdefghijklmnopqrstuvwxyz # Mantenha esta linha como está

# Nome de exibição do seu Fluxo de Trabalho
workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1 # Tipo de máquina que vai compilar

    environment:
      # Use sua versão do Flutter (a que você está usando)
      flutter: latest
      # Variáveis de ambiente
      groups:
        # AQUI VAI O NOME DO GRUPO DE VARIÁVEIS ONDE VOCÊ SALVOU O google-services.json
        # Ex: Se você nomeou seu grupo de arquivos secretos como 'firebase_credentials', use:
        - firebase_secrets

    # Onde o código-fonte deve ser limpo/iniciado
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages get

      - name: Setup Firebase Config (CRUCIAL)
        # Este script copia o arquivo google-services.json do Codemagic para a pasta correta:
        script: | 
          # Certifique-se de que o nome do arquivo aqui é o mesmo que você subiu!
          cp $CM_SECRETS/google-services.json $CM_BUILD_DIR/android/app/google-services.json

      - name: Flutter build APK
        script: |
          # Comando para construir o arquivo APK final
          flutter build apk --release

    artifacts:
      # O Codemagic vai salvar o APK gerado
      - build/app/outputs/flutter-apk/app-release.apk