appId: 1234567890abcdefghijklmnopqrstuvwxyz

workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      groups:
        - firebase_secrets 
      
    scripts:
      - name: Clean Gradle and Get Packages (Novo Passo)
        script: |
          flutter clean
          rm -rf $CM_BUILD_DIR/android/.gradle
          flutter packages get

      - name: Setup Firebase Config (CRUCIAL)
        script: | 
          cp "$CM_SECRETS/google-services.json" "$CM_BUILD_DIR/android/app/google-services.json" || true
          cp -f "$CM_BUILD_DIR/google-services.json" "$CM_BUILD_DIR/android/app/google-services.json" || true
          ls -la "$CM_BUILD_DIR/android/app/google-services.json" # Diagnóstico

      - name: Flutter build APK (Com Flag de Bypass)
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
          
          ls -R build/app/outputs/ # Repetir para ver o novo caminho

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk


